config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_up: 'signup', sign_out: 'logout' }, controllers: { registrations: 'registrations' }

  resources :quizzes, param: :slug do
    resources :events, only: [:index, :create, :destroy] do
      member do
        post "toggle_attending", to: "events#toggle_attending"
      end
    end
    member do
      post "toggle_favorite", to: "quizzes#toggle_favorite"
    end
  end

  get "/favourites" => "favorites#index"
  get "/my_quizzes" => "quizzes#my_quizzes"
  get "/calendar" => "quizzes#calendar"
  get "/map" => "quizzes#map"

  root "quizzes#index"
  resources :users
  
  get "/sitemap.xml" => "sitemap#index", :format => "xml", :as => :sitemap
  get "/:page" => "static#show"
end

app/views/layouts/_filters.html.erb
<div class="filters">
  <div class="filter-zone">
    <% if !@filters.empty? %>
      <div class="results-label">
        <h3>Quizzes
          <% @filters.each do |param| %>
            <%= param[1] != "" && param[0] != "sorts" ? getFilterPrefix(param[0]) : "" %>
            <%= param[0] != "sorts" ? param[1] : "" %>
          <% end %>
        </h3>
        <%= link_to "Clear", current_page?("/map") ? "/map" : root_path, class: "icon-link action" %>
      </div>
    <% else %>
      <h3>Regular pub quizzes in Bristol, UK</h3>
    <% end %>
    <%= search_form_for @search, url: current_page?("/map") ? map_path : root_path do |f| %>
      <div class="quiz-search">
        <div class="filter input-with-attachment">
          <%= f.text_field :venue_cont, placeholder: "Search venues...", onchange: 'this.form.submit()' %>
          <%= button_tag do %>
            <%= fa_icon "search" %>
          <% end %>
        </div>
        <%= f.select :day_cont, [["Any day", ""], "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"], {prompt: "Day"}, {onchange: 'this.form.submit()'} %>
        <%= f.select :postcode_cont, [["All", ""], ["Centre", "BS1"], ["Kingsdown / St Paul’s", "BS2"], ["Bedminster / Southville", "BS3"], ["Knowle / Brislington", "BS4"], ["Easton", "BS5"], ["Redland", "BS6"], ["Bishopston / Horfield", "BS7"], ["Clifton", "BS8"]], {prompt: "Location"}, {onchange: 'this.form.submit()'} %>
      </div>
      <div class="options-container">
        <div class="active-checkbox">
          <label><%= f.check_box :status_start, { onclick: "this.form.submit()" }, "active", "" %>Currently active quizzes only</label>
        </div>
        <div class="tabs-container">
          <%= link_to "List view", root_path, class: "tab-link#{" active-tab" if !current_page?("/map")}" %>
          <%= link_to "Map view", "/map", class: "tab-link#{" active-tab" if current_page?("/map")}" %>
          <% if current_page?("/map") %>
            <%= button_tag id: "meet_in_the_middle", type: "button", class: "icon-link action" do %>
              <%= fa_icon "search" %><span> Meet in the middle</span>
            <% end %>
          <% else %>
            <div class="sort-container">
              <select id="sort_select">
                <option value="">A-Z</option>
                <option value="distance">Nearest</option>
              </select>
              <div id="postcode_form" class="input-with-attachment">
                <%= f.text_field :sorts, placeholder: "Enter a postcode" %>
                <%= button_tag do %><%= fa_icon "arrow-right" %><% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-inner">
    <div>
      <%= link_to "/about", title: "About" do %>
        <%= fa_icon "info-circle", class: "fa-lg" %>About
      <% end %>
      <a href="mailto:<%= t('contact_email') %>" class="margin"><%= fa_icon 'envelope' %>Contact</a>
    </div>
    <span>© <%= Time.current.year %> Kate Howard</span>
  </div>
</footer

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <span>
      <%= value %>
    </span>
    <a href="#" data-dismiss="alert" class="close"><%= fa_icon "times" %></a>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav>
  <div class="nav-inner">
    <%= link_to quizzes_path, title: "Home", class: "nav-link" do %>
      <h1 class="link-lg"><%= fa_icon "home", class: "fa-lg", id: "home-icon" %><span class="nav-link-heading">Briz Quiz List</span></h1>
    <% end %>
    <% if user_signed_in? %>
      <%= link_to calendar_path, title: "Calendar", class: "nav-link#{" active" if current_page?("/calendar")}" do %>
        <div><%= fa_icon "calendar-check-o", class: "fa-lg" %><span class="nav-link-heading">Calendar</span></div>
      <% end %>
      <%= link_to favourites_path, title: "Faves", class: "nav-link#{" active" if current_page?("/favourites")}" do %>
        <div><%= fa_icon "heart", class: "fa-lg" %><span class="nav-link-heading">Faves</span></div>
      <% end %>
    <% end %>
    <div class="account-container">
      <div class="account-link">
        <% if user_signed_in? %>
          <%= avatar_for(current_user) %>
        <% else %>
          <%= fa_icon "user-circle", class: "fa-lg" %>
        <% end %>
        <%= fa_icon "chevron-down", class: "fa-sm" %>
      </div>
      <div class="account-menu">
        <div class="account-menu-marker"></div>
        <div class="account-menu-list">
          <% if user_signed_in? %>
            <%= link_to edit_user_registration_path do %>
              <div class="icon-link"><%= fa_icon "user" %> <%= truncate(current_user.username || current_user.email, length: 25) %></div>
            <% end %>
            <% if current_user.try(:admin?) %>
              <%= link_to users_path do %>
                <div class="icon-link"><%= fa_icon "users" %> Users</div>
              <% end %>
            <% end %>
            <%= link_to my_quizzes_path do %>
              <div class="icon-link"><%= fa_icon "home" %> My Quizzes</div>
            <% end %>
            <%= link_to new_quiz_path do %>
              <div class="icon-link"><%= fa_icon "plus" %> New quiz</div>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <div class="icon-link"><%= fa_icon "sign-out" %> Log out</div>
            <% end %>
          <% else %>
            <%= link_to new_user_session_path do %>
              <div class="icon-link"><%= fa_icon "sign-in" %> Log in</div>
            <% end %>
            <%= link_to new_user_registration_path do %>
              <div class="icon-link"><%= fa_icon "user-plus" %> Sign up</div>
            <% end %>
          <% end %>
        </div>
      </div>
      </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title><%= title %></title>
    <meta name="description" content="<%= t('description') %>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta property="og:type" content="website">
    <meta property="og:url" content="<%= request.original_url %>">
    <meta property="og:title" content="<%= title %>">
    <meta property="og:description" content="<%= t('description') %>">
    <meta property="og:image" content="<%= asset_url("BrizQuizList.png") %>">

    <%= yield(:head_tags) %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script async src="https://w.appzi.io/bootstrap/bundle.js?token=8la8Q"></script>
    <%= favicon_link_tag asset_path('apple-touch-icon.png'), rel: "apple-touch-icon", sizes: "180x180" %>
    <%= favicon_link_tag asset_path('favicon-32x32.png'), rel: "icon", type: "image/png", sizes: "32x32" %>
    <%= favicon_link_tag asset_path('favicon-16x16.png'), rel: "icon", type: "image/png", sizes: "16x16" %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>